spring:
   datasource:
      url: jdbc:h2:file:///D:/Kalpana_Java_Project/devDb
      username: sa
      dirverClassName: org.h2.Driver
      platform: h2
   jpa:
      show-sql: true
      open-in-view: true
      hibernate:
         ddl-auto: validate
flyway:
   locations:classpath:db/migration
